In [1]:
import torch
import numpy as np



In [180]:
# everything is a tensor

x = torch.randn(3, requires_grad=True)
print(x)


y = (x * 2 *x)
print(y)
print(x.grad)

with torch.no_grad():
    b = x+x
    print(b)

print(x)

v = torch.tensor([.1, 1, .001], dtype=torch.float32)
y.backward(v)
print(x.grad)


tensor([ 0.4046,  0.3646, -1.3677], requires_grad=True)
tensor([0.3274, 0.2659, 3.7412], grad_fn=<MulBackward0>)
None
tensor([ 0.8092,  0.7293, -2.7354])
tensor([ 0.4046,  0.3646, -1.3677], requires_grad=True)
tensor([ 0.1618,  1.4585, -0.0055])


In [88]:
# reshape() is valled view()
# view takes the shape. A dim  axis can be set to -1, which makes pytorch figure out this dimension on its own so it matches.
# only one can be inferred. You can call reshape as well. Also, size() is equivalent to .shape -NICE!


# print(x[:])
# y = y.reshape((2,-1,2))

# careful this creates a view, sharing memory. Not a copy.torch

y_numpy = y.numpy()




In [123]:
help(y.backward)

Help on method backward in module torch.tensor:

backward(gradient=None, retain_graph=None, create_graph=False) method of torch.Tensor instance
    Computes the gradient of current tensor w.r.t. graph leaves.
    
    The graph is differentiated using the chain rule. If the tensor is
    non-scalar (i.e. its data has more than one element) and requires
    gradient, the function additionally requires specifying ``gradient``.
    It should be a tensor of matching type and location, that contains
    the gradient of the differentiated function w.r.t. ``self``.
    
    This function accumulates gradients in the leaves - you might need to zero
    ``.grad`` attributes or set them to ``None`` before calling it.
    See :ref:`Default gradient layouts<default-grad-layouts>`
    for details on the memory layout of accumulated gradients.
    
    Arguments:
        gradient (Tensor or None): Gradient w.r.t. the
            tensor. If it is a tensor, it will be automatically converted
         

In [120]:
y.add_(2)
print(y_numpy)weight  =  torch.tensor(1.0, requires_grad=True)
x  =  torch.tensor(1.0)
y = torch.tensor(2.0)

# forward
y_hat = x*weight
s = y_hat-y
loss = s**2
print(loss)

# backward
loss.backward()
print(weight.grad)

weight = .5 * weight.grad
weight.grad.
print(weight.grad)

[[[2.3306563 2.869709 ]
  [2.9119813 2.0588164]
  [2.1858974 2.575907 ]
  [2.325669  2.0668252]]

 [[2.234551  2.8456798]
  [2.3934216 2.854475 ]
  [2.7995362 2.2161026]
  [2.3276508 2.1408634]]

 [[2.8381882 2.1294775]
  [2.9853559 2.0090108]
  [2.2017255 2.1800888]
  [2.6940227 2.801777 ]]

 [[2.524401  2.1162524]
  [2.8681056 2.2842507]
  [2.683022  2.7785275]
  [2.2807288 2.202453 ]]]


In [ ]:
# everything is a tensor

weights = torch.ones(4, requires_grad=True)

alpha=.01
optimizer = torch.optim.SGD(weights, lr=alpha)
for epoch in range( 2):
    out = (weights*3).sum()
    out.backward()

    print(weights.grad)
    optimizer.step()
    # weights -= alpha*out.grad

    weights.grad.zero_()





In [25]:
import torch
import torch.nn as nn


X = torch.tensor([1,2,3,4], dtype=torch.float32)
Y = torch.tensor([2,4,6,8], dtype=torch.float32)


# manually
# w = torch.tensor(0.8, requires_grad=True)
# forward = lambda x: w*x
model = nn.Linear(4,1)
#manually:
# loss = lambda y, y_hat: ((y-y_hat)**2).mean()
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), .02)

for epoch in range(100):
    y_pred = model(X)
    l = loss(y_pred, Y)
    [w, b] = model.parameters()
    print(f'Epoch:{epoch} Loss {l.item():.3f}, w:{w[0]}')

    # either:
    l.backward()
    with torch.no_grad():
        #manual
        # w -= (.1 * w.grad)
        optimizer.step()
        optimizer.zero_grad()

    # or manually:
    # grad = lambda y_pred: np.dot(2*X, (y_pred-Y)).mean()
    # g = grad(y_pred)



    print()
    print()
    print()


Epoch:0 Loss 15.535, w:tensor([ 0.2424,  0.0567,  0.3456, -0.0301], grad_fn=<SelectBackward>)



Epoch:1 Loss 5.607, w:tensor([0.3722, 0.3164, 0.7351, 0.4892], grad_fn=<SelectBackward>)



Epoch:2 Loss 5.035, w:tensor([0.3411, 0.2540, 0.6417, 0.3645], grad_fn=<SelectBackward>)



Epoch:3 Loss 5.002, w:tensor([0.3485, 0.2690, 0.6641, 0.3945], grad_fn=<SelectBackward>)



Epoch:4 Loss 5.000, w:tensor([0.3468, 0.2654, 0.6587, 0.3873], grad_fn=<SelectBackward>)



Epoch:5 Loss 5.000, w:tensor([0.3472, 0.2663, 0.6600, 0.3890], grad_fn=<SelectBackward>)



Epoch:6 Loss 5.000, w:tensor([0.3471, 0.2661, 0.6597, 0.3886], grad_fn=<SelectBackward>)



Epoch:7 Loss 5.000, w:tensor([0.3471, 0.2661, 0.6598, 0.3887], grad_fn=<SelectBackward>)



Epoch:8 Loss 5.000, w:tensor([0.3471, 0.2661, 0.6598, 0.3887], grad_fn=<SelectBackward>)



Epoch:9 Loss 5.000, w:tensor([0.3471, 0.2661, 0.6598, 0.3887], grad_fn=<SelectBackward>)



Epoch:10 Loss 5.000, w:tensor([0.3471, 0.2661, 0.6598, 0.3887], grad_fn=<Se

In [9]:
# 1) design model - input/output size forward pass
# 2) define loss and optimizer  
# 3) training loop:
#       - forward pass
#       - backward pass
#       - update weights

print(help(nn.Linear))


ights)
 |          Linear(in_features=2, out_features=2, bias=True)
 |          Parameter containing:
 |          tensor([[ 1.,  1.],
 |                  [ 1.,  1.]])
 |          Linear(in_features=2, out_features=2, bias=True)
 |          Parameter containing:
 |          tensor([[ 1.,  1.],
 |                  [ 1.,  1.]])
 |          Sequential(
 |            (0): Linear(in_features=2, out_features=2, bias=True)
 |            (1): Linear(in_features=2, out_features=2, bias=True)
 |          )
 |          Sequential(
 |            (0): Linear(in_features=2, out_features=2, bias=True)
 |            (1): Linear(in_features=2, out_features=2, bias=True)
 |          )
 |  
 |  bfloat16(self: ~T) -> ~T
 |      Casts all floating point parameters and buffers to ``bfloat16`` datatype.
 |      
 |      Returns:
 |          Module: self
 |  
 |  buffers(self, recurse: bool = True) -> Iterator[torch.Tensor]
 |      Returns an iterator over module buffers.
 |      
 |      Args:
 |          rec

In [47]:
import torch
import numpy as np
import torch.nn as nn
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

bc = datasets.load_breast_cancer()
X,y = bc.data, bc.target

nsamples = y.shape
nfeatures = x.shape[1]


X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=.2, random_state=42)

sc = StandardScaler().fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

X_train = torch.from_numpy(X_train.astype(torch.float32))
X_test = torch.from_numpy(X_test.astype(torch.float32))

y_train = torch.from_numpy(y_train.astype(torch.float32))
y_test = torch.from_numpy(y_test.astype(torch.float32))

y_train.t_()


TypeError: from_numpy() takes no keyword arguments